name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - run: |
          mkdir -p b
          cp -r lib/* b/
          cp android/app/google-services.json . 
          flutter create . --overwrite --org com.vikas.pasoriya
          # ऐप का असली नाम यहाँ सेट होगा
          sed -i 's/android:label=".*"/android:label="Vikas Pasoriya Official"/g' android/app/src/main/AndroidManifest.xml
          rm -rf lib/
          mv b lib/
          mv google-services.json android/app/
          sed -i 's/minSdkVersion 19/minSdkVersion 21/g' android/app/build.gradle
          flutter pub add cloud_firestore firebase_core url_launcher
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Vikas_Ultra_Max
          path: build/app/outputs/flutter-apk/app-release.apk
